
markdown: kramdown
kramdown:
  # use Github Flavored Markdown
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  # do not replace newlines by <br>s
  hard_wrap: false

sass:
    style: :compressed

excerpt_separator: <!--more-->

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
