markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
    style: :compressed

excerpt_separator: <!--more-->

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


# Used for Disqus.
# https://desiredpersona.com/disqus-comments-jekyll/
disqus:
   shortname: machinelearningnotes-1

collections:
    courses:
        output: true
